# -*- coding: utf-8 -*-
"""data_viz2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1Vjhlq2BX493gDaA_9nCEv4pV6NzMHu
"""

#Loading libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api

#Importing files from local
from google.colab import files
uploaded = files.upload()

#Read and prepare dataframe
df = pd.read_excel('df_stat.xlsx')
df.drop(['Img_path', 'Mask_path', 'Count'], axis = 1, inplace = True)
df.head(1)

#Importing files from local
from google.colab import files
uploaded = files.upload()

#Read and prepare dataframe
df_masked = pd.read_excel('df_stat_masked.xlsx')
df_masked.drop(['Img_path', 'Mask_path'], axis = 1, inplace = True)
df_masked = df_masked.iloc[:,0:4]
df_masked.head(1)

#Importing file from local
from google.colab import files
uploaded = files.upload()

#Read and prepare dataframe
df_prep = pd.read_excel('df_stat_preprocessed_v2.xlsx')
df_prep.head(1)

#Create correlation matrix to check correlation between statistical variables
df_num = df.select_dtypes('number')

sns.heatmap(df_num.corr(), annot=True);

#Investigate min and max min
print(df_num['Min'].mean())
print(df_num['Min'].max())

#Investigate max and min max
print(df_num['Max'].mean())
print(df_num['Max'].min())

#Mean, Std, Skewness, Kurtosis

#Save file
plt.savefig('/content/heatmap.png', bbox_inches = 'tight')

#Display file
plt.show()

#Download file to local
files.download('/content/heatmap.png')

#Create boxplots by source for six statistical variables (mean, std, min, max, kurtosis, skewness)
fig, axs = plt.subplots(3, 2, figsize=(10, 15))

#create subplot 1, fliersize determines the size of outliers
sns.boxplot(x ='URL', y ='Mean', data = df, fliersize=1.5, color = 'darkred', ax = axs[0, 0])
#Set x tick labels
axs[0, 0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[0, 0].set_title('Mean Values', fontsize = 12)
axs[0, 0].set_xlabel('Source')
axs[0, 0].set_ylabel('Mean')

#create subplot 2, fliersize determines the size of outliers
sns.boxplot(x ='URL', y ='Std_dev', data = df, fliersize=1.5, color = 'darkred', ax = axs[0, 1])
#Set x tick labels
axs[0, 1].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[0, 1].set_title('Standard deviation', fontsize = 12)
axs[0, 1].set_xlabel('Source')
axs[0, 1].set_ylabel('Standard deviation')

#create subplot 3, fliersize determines the size of outliers
sns.boxplot(x ='URL', y ='Min', data = df, fliersize=1.5, color = 'darkred', ax = axs[1, 0])
#Set x tick labels
axs[1, 0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[1, 0].set_title('Min Values', fontsize = 12)
axs[1, 0].set_xlabel('Source')
axs[1, 0].set_ylabel('Min')

#create subplot 4, fliersize determines the size of outliers
sns.boxplot(x ='URL', y ='Max', data = df, fliersize=1.5, color = 'darkred', ax = axs[1, 1])
#Set x tick labels
axs[1, 1].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[1, 1].set_title('Max Values', fontsize = 12)
axs[1, 1].set_xlabel('Source')
axs[1, 1].set_ylabel('Max')

#create subplot 5, fliersize determines the size of outliers
sns.boxplot(x ='URL', y ='Skewness', data = df, fliersize=1.5, color = 'darkred', ax = axs[2, 0])
#Set x tick labels
axs[2, 0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[2, 0].set_title('Skewness', fontsize = 12)
axs[2, 0].set_xlabel('Source')
axs[2, 0].set_ylabel('Skewness')

#create subplot 6, fliersize determines the size of outliers
sns.boxplot(x ='URL', y ='Kurtosis', data = df, fliersize=1.5, color = 'darkred', ax = axs[2, 1])
#Set x tick labels
axs[2, 1].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[2, 1].set_title('Kurtosis', fontsize = 12)
axs[2, 1].set_xlabel('Source')
axs[2, 1].set_ylabel('Kurtosis')
axs[2, 1].set_ylim(-2, 12)

plt.show()

#Create countplot and boxplots for each source for mean values and standard deviation
fig, axs = plt.subplots(2, 2, figsize=(10, 10))

#Create countplot
sns.countplot(x = 'URL', data = df, color = 'darkred', ax = axs[0,0])
#Set x tick labels
axs[0,0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[0,0].set_title('Count', fontsize = 12)
axs[0,0].set_xlabel('Source', fontsize = 11)
axs[0,0].set_ylabel('Count', fontsize = 11)

#Create empty plot
axs[0, 1].axis('off')

#Create subplot 1 (distribution of mean values per source)
sns.boxplot(x ='URL', y ='Mean', data = df, fliersize = 1.5, color = 'darkred', ax = axs[1,0])
#Set x tick labels
axs[1,0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[1,0].set_title('Mean Values', fontsize = 12)
axs[1,0].set_xlabel('Source', fontsize = 11)
axs[1,0].set_ylabel('Mean', fontsize = 11)

#Create subplot 1 (distribution of standard deviations per source)
sns.boxplot(x ='URL', y ='Std_dev', data = df, fliersize = 1.5, color = 'darkred', ax = axs[1,1])
#Set x tick labels
axs[1,1].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[1,1].set_title('Standard deviation', fontsize = 12)
axs[1,1].set_xlabel('Source', fontsize = 11)
axs[1,1].set_ylabel('Standard deviation', fontsize = 11)

#Save figure
plt.savefig('/content/boxplt_x.png')

plt.show()

#Dowload figure to local
files.download('/content/boxplt_x.png')

#Check the number of observations per source
n_source = df['URL'].value_counts()
n_source

#Split the dataset by source and extract a random sample of n = 119 for each case
S1 = df[df['URL'] == 'https://sirm.org/category/senza-categoria/covid-19/']
S2 = df[df['URL'] == 'https://github.com/ieee8023/covid-chestxray-dataset'].sample(n=119)
S3 = df[df['URL'] == 'https://github.com/ml-workgroup/covid-19-image-repository/tree/master/png'].sample(n=119)
S4 = df[df['URL'] == 'https://eurorad.org'].sample(n=119)
S5 = df[df['URL'] == 'https://github.com/armiro/COVID-CXNet'].sample(n=119)
S6 = df[df['URL'] == 'https://bimcv.cipf.es/bimcv-projects/bimcv-covid19/#1590858128006-9e640421-6711'].sample(n=119)
S7 = df[df['URL'] == 'https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia'].sample(n=119)
S8 = df[df['URL'] == 'https://www.kaggle.com/c/rsna-pneumonia-detection-challenge/data'].sample(n=119)
#Concat the downsampled dataframes
df_sample = pd.concat([S1, S2, S3, S4, S5, S6, S7, S8])
#Check length of dataframe
len(df_sample) == 119*8

#Create countplot and boxplots for each source for mean values and standard deviation from the new downsampled data set
fig, axs = plt.subplots(1, 3, figsize=(15, 5))

#Create countplot
sns.countplot(x = 'URL', data = df_sample, color = 'darkred', ax = axs[0])
#Set x tick labels
axs[0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[0].set_title('Count', fontsize = 12)
axs[0].set_xlabel('Sorce')
axs[0].set_ylabel('Count')

#Create subplot 1 (distribution of mean values per source) (downsampled data set)
sns.boxplot(x ='URL', y ='Mean', data = df_sample, fliersize = 1.5, color = 'darkred', ax = axs[1])
#Set x tick labels
axs[1].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[1].set_title('Mean Values', fontsize = 12)
axs[1].set_xlabel('Source')
axs[1].set_ylabel('Mean')

#Create subplot 1 (distribution of mean values per source) (downsampled data set)
sns.boxplot(x ='URL', y ='Std_dev', data = df_sample, fliersize = 1.5, color = 'darkred', ax = axs[2])
#Set x tick labels
axs[2].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[2].set_title('Standard deviation', fontsize = 12)
axs[2].set_xlabel('Source')
axs[2].set_ylabel('Standard deviation')

plt.show()

#Create qq-plot for each subgroup (sources) to check for normal dsitribution
mean_values = S1['Mean']

plt.figure(figsize = (5, 5))
#Create qq-plot from mean values
stats.probplot(mean_values, dist = "norm", plot = plt)
plt.title('Q-Q Plot of Mean Values', fontsize = 12)
plt.xlabel('Theoretical Quantiles')
plt.ylabel('Sample Quantiles')

#Save figure
plt.savefig('/content/qq_plot.png')

plt.show()

#Download figure
files.download('/content/qq_plot.png')

#Create qq-plot for each subgroup (sources) to check for normal dsitribution
std_values = S1['Std_dev']

plt.figure(figsize = (5, 5))
#Create qq-plot from std_dev values
stats.probplot(std_values, dist = "norm", plot = plt)
plt.title('Q-Q Plot of Standard deviations', fontsize = 12)
plt.xlabel('Theoretical Quantiles')
plt.ylabel('Sample Quantiles')

plt.show()

#Conduct ANOVA to check whether the source of the images has a significant effect on mean values

#𝐻0:There is no significant effect of the categorical source variable on the continuous mean variable
#𝐻1:There is a significant effect of the categorical source variable on the continuous mean variable

#ANOVA test using statsmodels library
result = statsmodels.formula.api.ols('Mean ~ URL', data = df_sample).fit()
table = statsmodels.api.stats.anova_lm(result)
display(table)

#Print output
print("Source has a significant influence on mean value.")

#Save and download test results to local
table.to_csv('/content/anova_results_mean.csv', index=False)
files.download('/content/anova_results_mean.csv')

#Conduct ANOVA to check whether the source of the images has a significant effect on standard deviations

#𝐻0:There is no significant effect of the categorical source variable on the continuous std_dev variable
#𝐻1:There is a significant effect of the categorical source variable on the continuous std_dev variable

#ANOVA test using statsmodels library
result = statsmodels.formula.api.ols('Std_dev ~ URL', data = df_sample).fit()
table = statsmodels.api.stats.anova_lm(result)
display(table)

#Print output
print("Source has significant influence on standard deviation.")

#Save and download test results to local
table.to_csv('/content/anova_results_std.csv', index=False)
files.download('/content/anova_results_std.csv')

#Upload files
from google.colab import files
uploaded = files.upload()

#Read and prepare dataframe (here statistics of entire x ray images with normalized pixel values)
df2 = pd.read_excel('df_stat_v2.xlsx')
df2.drop(['Img_path', 'Mask_path', 'Count'], axis = 1, inplace = True)
df2.head(1)

#Split the dataset by source and extract a random sample of n = 119 for each case
S1 = df2[df2['URL'] == 'https://sirm.org/category/senza-categoria/covid-19/']
S2 = df2[df2['URL'] == 'https://github.com/ieee8023/covid-chestxray-dataset'].sample(n=119)
S3 = df2[df2['URL'] == 'https://github.com/ml-workgroup/covid-19-image-repository/tree/master/png'].sample(n=119)
S4 = df2[df2['URL'] == 'https://eurorad.org'].sample(n=119)
S5 = df2[df2['URL'] == 'https://github.com/armiro/COVID-CXNet'].sample(n=119)
S6 = df2[df2['URL'] == 'https://bimcv.cipf.es/bimcv-projects/bimcv-covid19/#1590858128006-9e640421-6711'].sample(n=119)
S7 = df2[df2['URL'] == 'https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia'].sample(n=119)
S8 = df2[df2['URL'] == 'https://www.kaggle.com/c/rsna-pneumonia-detection-challenge/data'].sample(n=119)
#Concat downsampled data subsets
df2_sample = pd.concat([S1, S2, S3, S4, S5, S6, S7, S8])
#Test length of dataframe
len(df2_sample) == 119*8

#Conduct ANOVA to check whether the source of the images has a significant effect on mean values (normalized pixel values)

#𝐻0:There is no significant effect of the categorical source variable on the continuous mean variable
#𝐻1:There is a significant effect of the categorical source variable on the continuous mean variable

#ANOVA test using statsmodels library
result = statsmodels.formula.api.ols('Mean ~ URL', data = df2_sample).fit()
table = statsmodels.api.stats.anova_lm(result)
display(table)

#Print output
print("Source has a significant influence on mean value.")

#Save and download test results to local
table.to_csv('/content/anova_results_mean.csv', index=False)
files.download('/content/anova_results_mean.csv')

#Conduct ANOVA to check whether the source of the images has a significant effect on standard deviations (normalized pixel values)

#𝐻0:There is no significant effect of the categorical source variable on the continuous std_dev variable
#𝐻1:There is a significant effect of the categorical source variable on the continuous std_dev variable

#ANOVA test using statsmodels library
result = statsmodels.formula.api.ols('Std_dev ~ URL', data = df2_sample).fit()
table = statsmodels.api.stats.anova_lm(result)
display(table)

#Print output
print("Source has significant influence on standard deviation.")

#Save and download test results to local
table.to_csv('/content/anova_results_std.csv', index=False)
files.download('/content/anova_results_std.csv')

#Create countplot and boxplot for each source for pixel count values
fig, axs = plt.subplots(1, 2, figsize=(12, 5))

#Create countplot
sns.countplot(x = 'URL', data = df_masked, color = 'blue', ax = axs[0])
#Set x tick labels
axs[0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[0].set_title('Count', fontsize = 12)
axs[0].set_xlabel('Source', fontsize = 11)
axs[0].set_ylabel('Count', fontsize = 11)

#Create boxplot
sns.boxplot(x ='URL', y ='Count', data = df_masked, fliersize = 1.5, color = 'blue', ax = axs[1])
#Set x tick labels
axs[1].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[1].set_title('Pixel count', fontsize = 12)
axs[1].set_xlabel('Source', fontsize = 11)
axs[1].set_ylabel('Pixel count', fontsize = 11)

#Save file
plt.savefig('/content/boxplt_2.png')

plt.show()

#Download file to local
files.download('/content/boxplt_2.png')

#Split the dataframe by source and retrieve a sample of each (n = 119)
S1_masked = df_masked[df_masked['URL'] == 'https://sirm.org/category/senza-categoria/covid-19/']
S2_masked = df_masked[df_masked['URL'] == 'https://github.com/ieee8023/covid-chestxray-dataset'].sample(n=119)
S3_masked = df_masked[df_masked['URL'] == 'https://github.com/ml-workgroup/covid-19-image-repository/tree/master/png'].sample(n=119)
S4_masked = df_masked[df_masked['URL'] == 'https://eurorad.org'].sample(n=119)
S5_masked = df_masked[df_masked['URL'] == 'https://github.com/armiro/COVID-CXNet'].sample(n=119)
S6_masked = df_masked[df_masked['URL'] == 'https://bimcv.cipf.es/bimcv-projects/bimcv-covid19/#1590858128006-9e640421-6711'].sample(n=119)
S7_masked = df_masked[df_masked['URL'] == 'https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia'].sample(n=119)
S8_masked = df_masked[df_masked['URL'] == 'https://www.kaggle.com/c/rsna-pneumonia-detection-challenge/data'].sample(n=119)
#Concant the splitted dataframe again
df_sample_masked = pd.concat([S1_masked, S2_masked, S3_masked, S4_masked, S5_masked, S6_masked, S7_masked, S8_masked])
#Test length of dataframe
len(df_sample_masked) == 119*8

#Create countplot and boxplot for each source for pixel count values (on new downsampled dataframe)
fig, axs = plt.subplots(1, 2, figsize=(12, 5))

#Create countplot
sns.countplot(x = 'URL', data = df_sample_masked, color = 'blue', ax = axs[0])
#Set x tick labeles
axs[0].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[0].set_title('Count', fontsize = 12)
axs[0].set_xlabel('Sorce')
axs[0].set_ylabel('Count')

#Create boxplot
sns.boxplot(x ='URL', y ='Count', data = df_sample_masked, fliersize = 1.5, color = 'blue', ax = axs[1])
#Set xtick labels
axs[1].set_xticklabels(['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8'])
axs[1].set_title('Pixel count', fontsize = 12)
axs[1].set_xlabel('Source')
axs[1].set_ylabel('Pixel count')

plt.show()

#Create qq-plots for each subgroup (by source) of dataframe (downsampled)
count_values = S1_masked['Count']

plt.figure(figsize = (5, 5))
#Create qq-plot
stats.probplot(count_values, dist = "norm", plot = plt)
plt.title('Q-Q Plot of pixel count values', fontsize = 12)
plt.xlabel('Theoretical Quantiles')
plt.ylabel('Sample Quantiles')

plt.show()

#Conduct ANOVA to check whether the source of the images has a significant effect on count values

#𝐻0:There is no significant effect of the categorical source variable on the continuous count variable
#𝐻1:There is a significant effect of the categorical source variable on the continuous count variable

#Conduct ANOVA using statsmodels library
result = statsmodels.formula.api.ols('Count ~ URL', data = df_sample_masked).fit()
table = statsmodels.api.stats.anova_lm(result)
display(table)

#Print result
print("Source has no significant influence on pixel count.")

#Save and download to local
table.to_csv('/content/anova_results_count.csv', index=False)
files.download('/content/anova_results_count.csv')

#Upload files
from google.colab import files
uploaded = files.upload()

#Read dataframe (masked images with normalized pixel values)
df2_masked = pd.read_excel('df_stat_masked_v2.xlsx')
df2_masked.head(1)

#Split the dataframe by source and retrieve a sample of each (n = 119)
S1_masked = df2_masked[df2_masked['URL'] == 'https://sirm.org/category/senza-categoria/covid-19/']
S2_masked = df2_masked[df2_masked['URL'] == 'https://github.com/ieee8023/covid-chestxray-dataset'].sample(n=119)
S3_masked = df2_masked[df2_masked['URL'] == 'https://github.com/ml-workgroup/covid-19-image-repository/tree/master/png'].sample(n=119)
S4_masked = df2_masked[df2_masked['URL'] == 'https://eurorad.org'].sample(n=119)
S5_masked = df2_masked[df2_masked['URL'] == 'https://github.com/armiro/COVID-CXNet'].sample(n=119)
S6_masked = df2_masked[df2_masked['URL'] == 'https://bimcv.cipf.es/bimcv-projects/bimcv-covid19/#1590858128006-9e640421-6711'].sample(n=119)
S7_masked = df2_masked[df2_masked['URL'] == 'https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia'].sample(n=119)
S8_masked = df2_masked[df2_masked['URL'] == 'https://www.kaggle.com/c/rsna-pneumonia-detection-challenge/data'].sample(n=119)
#Concat splitted dataframes again
df2_sample_masked = pd.concat([S1_masked, S2_masked, S3_masked, S4_masked, S5_masked, S6_masked, S7_masked, S8_masked])
#Check length of dataframe
len(df2_sample_masked) == 119*8

#Conduct ANOVA to check whether the source of the images has a significant effect on count values (now normalized pixel values)

#𝐻0:There is no significant effect of the categorical source variable on the continuous count variable
#𝐻1:There is a significant effect of the categorical source variable on the continuous count variable

#Conduct ANOVA using statsmodels library
result = statsmodels.formula.api.ols('Count ~ URL', data = df2_sample_masked).fit()
table = statsmodels.api.stats.anova_lm(result)
display(table)

#Print result
print("Source has no significant influence on pixel count.")

#Save results and download to local
table.to_csv('/content/anova_results_count.csv', index=False)
files.download('/content/anova_results_count.csv')

#Add colum to df_pre and df_masked, defining the level of pre processing (df_pred, pre processed images, df_masked, only masked)
df_prep['Level'] = 'L2'
df_masked['Level'] = 'L1'
#Concat df_pred and df_masked
df_all = pd.concat([df_prep, df_masked])
df_all.head(1)

#Create boxplots for each source and pre processing level
fig, axs = plt.subplots(2, 2, figsize=(12, 15))

#Create countplot
sns.countplot(x = 'Case', data = df_all[df_all['Level'] == 'L1'], color = 'darkred', ax = axs[0,0])
axs[0,0].set_title('Count', fontsize = 12)
axs[0,0].set_xlabel('Case', fontsize = 11)
axs[0,0].set_ylabel('Count', fontsize = 11)

#Create empty plot
axs[0, 1].axis('off')

#Create boxplots of the distribution of kurtosis for each source and pre processing level
sns.boxplot(x ='Case', y ='Kurtosis', data = df_all, hue = 'Level', fliersize = 1.5, color = 'darkred', ax = axs[1,0])
axs[1,0].set_title('Kurtosis', fontsize = 12)
axs[1,0].set_xlabel('Case', fontsize = 11)
axs[1,0].set_ylabel('Kurtosis', fontsize = 11)

#Create boxplots of the distribution of skewness for each source and pre processing level
sns.boxplot(x ='Case', y ='Skewness', data = df_all, hue = 'Level', fliersize = 1.5, color = 'darkred', ax = axs[1,1])
axs[1,1].set_title('Skewness', fontsize = 12)
axs[1,1].set_xlabel('Case', fontsize = 11)
axs[1,1].set_ylabel('Skewness', fontsize = 11)

#Save figure
plt.savefig('/content/boxplt_1.png')

plt.show()

#Download figure
files.download('/content/boxplt_1.png')